MySite/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name='home-page'),
    path('Register/', views.register, name='register-user-page'),
    path('login/', views.login_view, name='login-page'),
    path('property-register/', views.property_register, name='register-property-page'),
    path('property/', views.property_view, name='property-page'),
    path('property/<int:property_id>', views.single_property, name='single-property-page'),
    path('upload/<int:property_id>', views.upload_view, name='upload-page'),
    path('search/', views.search_view, name='search-results-page'),
    path('review/<int:property_id>', views.review_submit, name='review-register-page'),
    path('logout/', views.logout_view, name='logout-page'),
    path('services', views.services, name='services-page'),
    path('about', views.about, name='about-page'),
    path('contact', views.contact, name='contact-page')
]

urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MySite.urls')),
]
urlpatterns += static(settings.DOC_URL, document_root=settings.DOC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MySite/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import MaxValueValidator
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.db.models import Avg


class User(AbstractUser):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    username = models.CharField(max_length=30, unique=True)
    password = models.CharField(max_length=255)
    email = models.EmailField(max_length=255, unique=True)


class ProfileUser(models.Model):
    birth_date = models.DateField(null=True, blank=True)
    phone_number = models.CharField(max_length=10, unique=True,
                                    validators=[
                                        MinLengthValidator(limit_value=10),
                                        MaxLengthValidator(limit_value=10),
                                    ])  # 0(912 345 6789)
    Owner = 'O'
    Tenant = 'T'
    UserNormal = 'U'
    ROLE_CHOICES = [
        (Owner, 'Owner'),
        (Tenant, 'Tenant'),
        (UserNormal, 'User'),
    ]
    role = models.CharField(
        max_length=1, choices=ROLE_CHOICES, default=UserNormal)
    requestRole = models.CharField(max_length=10, default='User')
    image = models.ImageField(upload_to='MySite/image', null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username}'

    def first_name(self):
        return self.user.first_name

    def last_name(self):
        return self.user.last_name

    def username(self):
        return self.user.username

    def password(self):
        return self.user.password

    def email(self):
        return self.user.email

    class Meta:
        verbose_name = 'User'


class Property(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=400)
    rent_price = models.DecimalField(max_digits=10, decimal_places=2, default=1000000)
    house_city = models.CharField(max_length=30)
    house_address = models.CharField(max_length=255)
    bedrooms = models.PositiveIntegerField(default=0)
    bathrooms = models.PositiveIntegerField(default=0)
    area = models.PositiveIntegerField(default=0)
    yard_area = models.PositiveIntegerField(default=0)
    year = models.PositiveIntegerField(validators=[MaxValueValidator(2099)], default=2000)
    garage = models.BooleanField(default=False)
    is_available = models.BooleanField(default=True)
    is_submit = models.BooleanField(default=False)
    house_review = models.FloatField(null=True, blank=True)
    house_quality = models.FloatField(null=True, blank=True)
    house_location = models.FloatField(null=True, blank=True)
    house_price = models.FloatField(null=True, blank=True)
    house_landlord = models.FloatField(null=True, blank=True)
    house_neighborhood = models.FloatField(null=True, blank=True)
    house_transportation = models.FloatField(null=True, blank=True)
    house_owner = models.ForeignKey(ProfileUser, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='MySite/image', null=True, blank=True)

    def update_average_rating(self):
        # Retrieve the average rating for the property
        average_rating = Review.objects.filter(property=self).aggregate(Avg('rating'))['rating__avg']
        average_quality = Review.objects.filter(property=self).aggregate(Avg('quality'))['quality__avg']
        average_location = Review.objects.filter(property=self).aggregate(Avg('location'))['location__avg']
        average_price = Review.objects.filter(property=self).aggregate(Avg('price'))['price__avg']
        average_landlord = Review.objects.filter(property=self).aggregate(Avg('landlord'))['landlord__avg']
        average_neighborhood = Review.objects.filter(property=self).aggregate(Avg('neighborhood'))['neighborhood__avg']
        average_transportation = Review.objects.filter(property=self).aggregate(
            Avg('transportation'))['transportation__avg']

        # Update reviews field
        self.house_review = round(average_rating, 2) if average_rating else 0
        self.house_quality = round(average_quality, 2) if average_quality else 0
        self.house_location = round(average_location, 2) if average_location else 0
        self.house_price = round(average_price, 2) if average_price else 0
        self.house_landlord = round(average_landlord, 2) if average_landlord else 0
        self.house_neighborhood = round(average_neighborhood, 2) if average_neighborhood else 0
        self.house_transportation = round(average_transportation, 2) if average_transportation else 0
        self.save()

    def __str__(self):
        return f"{self.title} - {self.house_owner.username}"

    class Meta:
        indexes = [
            models.Index(fields=['title'])
        ]
        ordering = ["is_submit", "is_available"]


class Document(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    uploader = models.ForeignKey(ProfileUser, on_delete=models.CASCADE)
    file = models.FileField(upload_to='documents/')
    STATUS_CHOICES = [
        ('Rejected', 'Rejected'),
        ('Pending', 'Pending'),
        ('Accepted', 'Accepted'),
    ]
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='Pending')
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.property.title} - {self.uploader.username}"

    class Meta:
        ordering = ['status']


class Review(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    tenant = models.ForeignKey(ProfileUser, on_delete=models.CASCADE)
    quality = models.PositiveIntegerField(default=1, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])
    location = models.PositiveIntegerField(default=1, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])
    price = models.PositiveIntegerField(default=1, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])
    landlord = models.PositiveIntegerField(default=1, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])
    neighborhood = models.PositiveIntegerField(default=1, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])
    transportation = models.PositiveIntegerField(default=1, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])
    rating = models.FloatField(default=1, editable=False)
    comment = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='Mysite/images', null=True, blank=True)

    def save(self, *args, **kwargs):
        # Calculate the average rating
        criteria_count = 6  # Number of criteria for evaluation
        total_rating = self.quality + self.location + self.price + self.landlord + self.neighborhood \
                                    + self.transportation
        self.rating = round(total_rating / criteria_count, 2)

        super().save(*args, **kwargs)

        # Update the average rating for the associated Property
        self.property.update_average_rating()

    def __str__(self):
        return f"{self.property.title} - {self.tenant.username}"

MySite/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Property, Review, Document
from .forms import LoginForm, UserForm, ProfileForm, PropertyForm, ReviewForm, DocumentForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password
import sweetify
from django.db.models import Q


def homepage(request):
    properties = Property.objects.select_related('house_owner').filter(is_submit=True)
    return render(request, 'index.html', {'properties': properties})


def services(request):
    return render(request, 'services.html')


def about(request):
    return render(request, 'about.html')


def contact(request):
    return render(request, 'contact.html')


def search_view(request):
    query = request.GET.get('query')
    msg = None
    properties = None
    if query:
        properties = Property.objects.select_related('house_owner').filter(Q(house_city__icontains=query)| Q(title__icontains=query))
        print(properties)
        context = {'properties': properties, 'query': query, 'msg': msg}
        return render(request, 'index.html', context)
    else:
        msg = 'Not Found'

    context = {'properties': properties, 'query': query, 'msg': msg}
    return render(request, 'index.html', context)


def property_view(request):
    properties = Property.objects.select_related('house_owner').filter(is_submit=True)
    return render(request, 'properties.html', {'properties': properties})


def single_property(request, property_id):
    prop = Property.objects.select_related('house_owner').get(id=property_id)
    comments = comments = Review.objects.filter(property_id=property_id).order_by('-time')
    comments_count = comments.count()
    return render(request, 'property-single.html', {'prop': prop, 'comments': comments,
                                                    'comments_count': comments_count})


def logout_view(request):
    logout(request)
    return redirect('login-page')


def register(request):
    msg = None
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST, request.FILES)
        if user_form.is_valid():
            if user_form.cleaned_data.get('password') == user_form.cleaned_data.get('confirm_password'):
                user = user_form.save(commit=False)
                hashed_password = make_password(user_form.cleaned_data['password'])
                # Create a user object but don't save
                user.password = hashed_password
                user.save()
                profile = profile_form.save(commit=False)
                profile.user = user  # Associate the profile with the user
                profile.save()
                return redirect('login-page')
            else:
                msg = 'Password should be equal to password confirm'
    else:
        user_form = UserForm()
        profile_form = ProfileForm()
    return render(request, 'register.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'msg': msg
    })


def login_view(request):
    if request.user.is_authenticated:
        return redirect('home-page')

    form = LoginForm(request.POST or None)
    msg = None

    if request.method == 'POST':

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home-page')
            else:
                msg = 'Invalid credentials'
        else:
            msg = 'Error validating the form'

    return render(request, 'login.html', {'form': form, 'msg': msg})


@login_required()
def property_register(request):
    if not request.user.is_staff:
        if request.user.profileuser.role == 'O':
            if request.method == 'POST':
                property_form = PropertyForm(request.POST, request.FILES)
                if property_form.is_valid():
                    property_instance = property_form.save(commit=False)
                    property_form.instance.house_owner = request.user.profileuser
                    property_form.save()
                    return redirect('home-page')
            else:
                property_form = PropertyForm()

            return render(request, 'propertyRegister.html', {
                'property_form': property_form
            })
        else:
            sweetify.error(request, 'Access Denied')
            return redirect('home-page')
    sweetify.error(request, 'Access Denied')
    return redirect('home-page')


@login_required()
def review_submit(request, property_id):
    if not request.user.is_staff:
        if request.user.profileuser.role == 'T':
            try:
                Document.objects.get(property_id=property_id, uploader_id=request.user.profileuser.id, status='Accepted')
                Review.objects.get(property_id=property_id, tenant_id=request.user.profileuser.id)
                sweetify.info(request, 'you already rate this house')
                return redirect('home-page')
            except Review.DoesNotExist:
                if request.method == 'POST':
                    review_form = ReviewForm(request.POST, request.FILES)
                    if review_form.is_valid():
                        prop = Property.objects.get(id=property_id)
                        review = review_form.save(commit=False)
                        review.tenant = request.user.profileuser
                        review.property = prop
                        review.save()
                        sweetify.success(request, 'Your review have been Submitted')
                        return redirect('single-property-page', property_id=property_id)
                else:
                    review_form = ReviewForm()

                return render(request, 'reviewRegister.html', {'form': review_form})
            except Document.DoesNotExist:

                sweetify.error(request, 'first Your doc should be accepted by admin')
                previous_url = request.META.get('HTTP_REFERER')
                return redirect(previous_url)

        else:
            sweetify.error(request, 'Access Denied')
            previous_url = request.META.get('HTTP_REFERER')
            return redirect(previous_url)
    sweetify.error(request, 'Access Denied, Admin Can Not Rate')
    previous_url = request.META.get('HTTP_REFERER')
    return redirect(previous_url)
        

@login_required()
def upload_view(request, property_id):
    if not request.user.is_staff:
        if request.user.profileuser.role == 'T':
            form = DocumentForm(request.POST or None, request.FILES or None)
            try:
                Document.objects.get(Q(property_id=property_id) &
                                    Q(uploader_id=request.user.profileuser.id) &
                                    (Q(status='Pending') | Q(status='Accepted')))
                sweetify.info(request, 'you uploaded your doc')
                return redirect('home-page')
            except Document.DoesNotExist:
                if request.method == 'POST':
                    form = DocumentForm(request.POST, request.FILES)
                    if form.is_valid():
                        property_instance = Property.objects.get(id=property_id)
                        upload = form.save(commit=False)
                        upload.file = request.FILES['file']
                        upload.property = property_instance
                        upload.uploader = request.user.profileuser
                        upload.save()
                        sweetify.success(request, 'Your doc have been uploaded. wait for admin to accept it')
                        previous_url = request.META.get('HTTP_REFERER')
                        return redirect(previous_url)
                    else:
                        form = DocumentForm()
                    return render(request, 'upload.html', {'form': form, 'msg': 'credentials incorrect'})
                else:
                    return render(request, 'upload.html', {'form': form})

        else:
            sweetify.error(request, 'Access Denied')
            return redirect('home-page')
    sweetify.error(request, 'Access Denied, Admin Can Not Upload Doc')
    previous_url = request.META.get('HTTP_REFERER')
    return redirect(previous_url)

MySite/templates/login.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">

<!DOCTYPE html>
<!-- Created By CodingNepal -->
<html lang="en" dir="ltr">
   <head>
      <meta charset="utf-8">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
       <title>
            Real-Estate &mdash; Login
       </title>
       <style>
           body{
               background-image: url('../../static/images/hero_bg_1.jpg');
           }
           .show-btn{
               background: #005555;
               color: white;
           }
           .show-btn:hover{
               background: #036464;
           }
           .container{
               backdrop-filter: blur(8px); /* Chrome and Opera */
               box-shadow: 0px 10px 15px 10px rgb(0 0 0 / 15%);
               background-color: rgb(228 228 228 / 15%);
           }
           input{
               border-radius: 4px;
               backdrop-filter: blur(8px); /* Chrome and Opera */
               box-shadow: 0px 10px 15px 10px rgb(0 0 0 / 15%);
               background-color: rgb(228 228 228 / 15%);
           }
           form .btn button{
               background: #005555;
           }
           form .btn button:hover{
               background: #036464;
           }
           ::placeholder {
              color: #f5f5f5;
              opacity: 0.5; /* Firefox */
           }
           form .signup-link a{
               color: #3bc4ea;
           }
           form .forgot-pass a{
               color: #3bc4ea;
           }
           .close-btn{
               color: #ffffff;
           }
       </style>
   </head>
   <body>
      <div class="center">
{#         <input type="checkbox" id="show">#}
{#         <label for="show" class="show-btn">View Form</label>#}

         <div class="container">
            <a href="{% url 'home-page' %}" >
                <span class="close-btn fas fa-times">
                </span>
            </a>
            <div class="text">
               Login Form
            </div>
            {% if msg %}
            <li style="color: red;"">{{ msg }}</li>
            {% endif %}
            <form method= POST>
               {% csrf_token %}
               <div class="data">
                  <label>username</label>
                  {{form.username}}
               </div>
               <div class="data">
                  <label>Password</label>
                  {{form.password}}
               </div>
               <div class="forgot-pass">
                  <a href="#">Forgot Password?</a>
               </div>
               <div class="btn">
                  <div class="inner"></div>
                  <button type="submit">login</button>
               </div>
               <div class="signup-link">
                  Not a member? <a href="{% url 'register-user-page' %}">Signup now</a>
               </div>
            </form>
         </div>
      </div>
   </body>
</html>

MySite/templates/property.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Attribute Display with Progress Bars</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 0;
            background: #333; /* Dark gray background */
            color: #fff; /* White text color */
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        section {
            max-width: 600px;
            width: 100%;
            padding: 30px;
            background: #444; /* Darker gray background */
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
            border-radius: 10px;
            text-align: center;
        }

        h1 {
            color: #2ecc71; /* Green title color */
            margin-bottom: 20px;
        }

        ul {
            list-style: none;
            padding: 0;
            text-align: left;
        }

        li {
            margin-bottom: 15px;
        }

        li strong {
            color: #c4c4c4; /* Green strong text color */
        }
    </style>
</head>
<body>

    <section>
        <h1>Attribute Display with Progress Bars</h1>
        <ul>
            <!-- Update the value dynamically with your actual data -->
            <li><strong>title:</strong> {{prop.title}}</li>
            <li><strong>Rate:</strong> {{prop.review}}</li>
            <li><strong>Quality:</strong> {{prop.quality}}</li>
            <li><strong>Location:</strong> {{prop.location}}</li>
            <li><strong>Price:</strong> {{prop.price}}</li>
            <li><strong>LandLord:</strong> {{prop.landlord}}</li>
            <li><strong>Neighborhood:</strong> {{prop.neighborhood}}</li>
            <li><strong>Transportation:</strong> {{prop.transportation}}</li>
        </ul>
    </section>

</body>
</html>

MySite/templates/propertyRegister.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/core.css' %}">
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Real-Estate &mdash; Register-Property</title>
    <style>
        body{
            background-image: url('../../static/images/hero_bg_3.jpg');
        }
        .container{
            backdrop-filter: blur(8px); /* Chrome and Opera */
            box-shadow: 0px 10px 15px 10px rgb(0 0 0 / 15%);
            background-color: rgb(228 228 228 / 15%);
        }
        .container .title::before{
          background: #005555;
        }
        form .button input{
           background: #005555;
         }
        form .button input:hover{
          /* transform: scale(0.99); */
          background: #036464;
        }
        input{
            border-radius: 4px;
            backdrop-filter: blur(8px); /* Chrome and Opera */
            box-shadow: 0px 10px 15px 10px rgb(0 0 0 / 15%);
            background-color: rgb(228 228 228 / 15%);
        }
        textarea{
            border-radius: 4px;
            backdrop-filter: blur(8px); /* Chrome and Opera */
            box-shadow: 0px 10px 15px 10px rgb(0 0 0 / 15%);
            background-color: rgb(228 228 228 / 15%);
        }
        ::placeholder {
          color: black;
          opacity: 1; /* Firefox */
        }
    </style>
</head>
<body>
  <div class="container">
    <div class="title">Registration</div>
    <div class="content">
      <form method= POST enctype="multipart/form-data">
        {% csrf_token %}
        <div class="property-details">
          <div class="input-box">
            <span class="details">Title</span>
            {{property_form.title}}
          </div>
          <div class="input-box">
            <span class="details">Description</span>
            {{property_form.description}}
          </div>
          <div class="input-box">
            <span class="details">Rent Price</span>
            {{property_form.rent_price}}
          </div>

            <div style="display: flex">
                          <div class="input-box"  style="width: 33%">
            <span class="details">City</span>
            {{property_form.house_city}}
          </div>
          <div class="input-box" style="width: 33%">
            <span class="details">Address</span>
            {{property_form.house_address}}
          </div>
            <div class="input-box" style="width: 33%">
                <span class="details">Bedrooms</span>
                {{property_form.bedrooms}}
            </div>
            </div>

            <div style="display: flex">
                <div class="input-box" style="width: 33%">
                <span class="details">Bathrooms</span>
                {{property_form.bathrooms}}
            </div>
            <div class="input-box" style="width: 33%">
                <span class="details">Area</span>
                {{property_form.area}}
            </div>
            <div class="input-box" style="width: 33%">
                <span class="details">yard</span>
                {{property_form.yard_area}}
            </div>
            </div>

            <div style="display: flex">
                <div class="input-box" style="width: 33%">
                <span class="details">Year</span>
                {{property_form.year}}
            </div>
            <div class="input-box">
                <span class="details" style="width: 33%">Garage</span>
                {{property_form.garage}}
            </div>
            <div class="input-box" style="width: 33%; padding-left: 20px;">
                <span class="details">Image</span>
                {{property_form.image}}
            </div>
            </div>


        </div>
        <div class="button">
          <input type="submit" value="Register">
        </div>
      </form>
    </div>
  </div>
</body>
</html>

MySite/templates/reviewRegister.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Real-Estate &mdash; Rating&Comment</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-image: url('../../static/images/hero_bg_1.jpg');
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        form {
            backdrop-filter: blur(8px); /* Chrome and Opera */
            box-shadow: 0px 10px 15px 10px rgb(0 0 0 / 15%);
            background-color: rgb(228 228 228 / 15%);
            padding: 20px;
            border-radius: 8px;
            width: 80%;
            max-width: 600px;
        }

        label {
            display: block;
            margin-bottom: 8px;
            font-weight: bold;
        }

        input, textarea {
            border-radius: 4px;
            backdrop-filter: blur(8px); /* Chrome and Opera */
            box-shadow: 0px 10px 15px 10px rgb(0 0 0 / 15%);
            background-color: rgb(228 228 228 / 15%);
            width: 100%;
            padding: 8px;
            margin-bottom: 12px;
            box-sizing: border-box;
            border: 1px solid #ccc;
        }

        input[type="range"]::-webkit-slider-thumb{
            -webkit-appearance: none;
            appearance: none;
            width: 40px;
            height: 40px;
            background-color: #1a1e21;
            border-radius: 50px;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        input::after {
            content: '5';
            color: #0b373f;
            font-size: 1rem;
            position: absolute;
            left: 101%;
            top: 26%;
        }

        input::before {
            content: '1';
            color: #0b373f;
            font-size: 1rem;
            position: absolute;
            left: -2%;
            top: 26%;
        }

        button {
            background-color: #005555;
            color: #fff;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
        }

        button:hover {
            background-color: #036464;
        }

        span{
            color: #036464;
        }

    </style>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="rating1">Rate quality: <span id="qualityValue">3</span></label>
        <input type="range" name="quality" value="3" min="1" max="5" required="" id="id_quality" oninput="updateValue('quality')">

        <label for="rating2">Rate location: <span id="locationValue">3</span></label>
        <input type="range" name="location" value="3" min="1" max="5" required="" id="id_location" oninput="updateValue('location')">

        <label for="rating3">Rate price: <span id="priceValue">3</span></label>
        <input type="range" name="price" value="3" min="1" max="5" required="" id="id_price" oninput="updateValue('price')">

        <label for="rating4">Rate landlord: <span id="landlordValue">3</span></label>
        <input type="range" name="landlord" value="3" min="1" max="5" required="" id="id_landlord" oninput="updateValue('landlord')">

        <label for="rating5">Rate neighborhood: <span id="neighborhoodValue">3</span></label>
        <input type="range" name="neighborhood" value="3" min="1" max="5" required="" id="id_neighborhood" oninput="updateValue('neighborhood')">

        <label for="rating6">Rate transportation: <span id="transportationValue">3</span></label>
        <input type="range" name="transportation" value="3" min="1" max="5" required="" id="id_transportation" oninput="updateValue('transportation')">
        <label for="comment5">Comment:</label>
        {{form.comment}}
        <label for="image">Image:</label>
        {{ form.image }}
        <button type="submit" value="Register">Submit</button>
    </form>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.6.5/sweetalert2.all.min.js"></script>
    <script>
        function updateValue(fieldName) {
            var input = document.getElementById('id_' + fieldName);
            var valueSpan = document.getElementById(fieldName + 'Value');
            valueSpan.textContent = input.value;
        }
    </script>
</body>
</html>
{% load sweetify %}
{% sweetify %}